language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: 5.5
      env:
        LARAVEL_VERSION: ^5.1
        ORCHESTRA_VERSION: ^3.1

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
  - travis_retry composer require illuminate/support:"${LARAVEL_VERSION}"
  - travis_retry composer require orchestra/testbench:"${ORCHESTRA_VERSION}"

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
