language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  LARAVEL_VERSION: "5.1.*"
  ORCHESTRA_VERSION: "3.1.*"

matrix:
  include:
    - php: 5.5.9
      env: LARAVEL_VERSION="5.1.*" ORCHESTRA_VERSION="3.1.*"
    - php: 5.5.9
      env: LARAVEL_VERSION="5.2.*" ORCHESTRA_VERSION="3.2.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.1.*" ORCHESTRA_VERSION="3.1.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.2.*" ORCHESTRA_VERSION="3.2.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.3.*" ORCHESTRA_VERSION="3.3.*"
    - php: 5.6
      env: LARAVEL_VERSION="5.4.*" ORCHESTRA_VERSION="3.4.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.1.*" ORCHESTRA_VERSION="3.1.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.2.*" ORCHESTRA_VERSION="3.2.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.3.*" ORCHESTRA_VERSION="3.3.*"
    - php: 7.0
      env: LARAVEL_VERSION="5.4.*" ORCHESTRA_VERSION="3.4.*"
    - php: 7.1
      env: LARAVEL_VERSION="5.1.*" ORCHESTRA_VERSION="3.1.*"
    - php: 7.1
      env: LARAVEL_VERSION="5.2.*" ORCHESTRA_VERSION="3.2.*"
    - php: 7.1
      env: LARAVEL_VERSION="5.3.*" ORCHESTRA_VERSION="3.3.*"
    - php: 7.1
      env: LARAVEL_VERSION="5.4.*" ORCHESTRA_VERSION="3.4.*"

before_install:
  - composer require "illuminate/support:${LARAVEL_VERSION}" --no-update --no-interaction
  - composer require "orchestra/testbench:${ORCHESTRA_VERSION}" --no-update --no-interaction --dev

install:
  - composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text

after_success:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then
      composer require codeclimate/php-test-reporter --no-interaction --dev;
      vendor/bin/test-reporter;
    fi
